/// Canonical module blueprints transcribed 1:1 from the delivered development
/// pages (public/legacy/*.html) — proximity lists, payment structures, stats,
/// and line-broken headings match the delivered DOM exactly.
type Module = { slug: string; title: string; kind: "GALLERY" | "FLOOR_PLAN" | "SPECIFICATIONS" | "LOCATION" | "VIDEO" | "BROCHURE" | "CUSTOM"; sortOrder: number; content: object };
type Template = { tagline: string; description: string; heroImage: string; modules: Module[] };

const floorPlans = (name: string, text: string): Module => ({ slug: "floor-plans", title: "Floor Plans", kind: "FLOOR_PLAN", sortOrder: 50, content: { text, items: ["A", "B", "C"].map((label) => ({ label: `Type ${label}`, image: `/legacy/assets/images/floor-plans/seven-x-seven-type-${label.toLowerCase()}.svg`, url: `/legacy/contact.html?project=${encodeURIComponent(name)}&request=floor-plan-${label.toLowerCase()}` })) } });

/// Payment plan per the delivered page: intro copy, Download Payment Plan
/// button (mailto), and four milestones each with its description line.
const paymentPlan = (name: string, text: string, items: { value: string; label: string; text: string }[]): Module => ({ slug: "payment-plan", title: "Payment Plan", kind: "CUSTOM", sortOrder: 60, content: { text, url: `mailto:info@kpd.ae?subject=${encodeURIComponent(`${name} Payment Plan`)}`, items } });

const calmPanel = (title: string, text: string, image: string, name: string): Module => ({ slug: "brochure", title, kind: "CUSTOM", sortOrder: 45, content: { presentation: "calm", text, images: [image], url: `/legacy/contact.html?project=${encodeURIComponent(name)}&request=brochure` } });

export const legacyProjectTemplates: Record<string, Template> = {
  "seven-x-seven": {
    tagline: "An address shaped\nby restraint",
    description: "Seven X Seven Residences sits within Meydan Horizon, planned around measured city access and the quiet rhythm of everyday living. The brief begins with how the home is used - arrival, light, and privacy - and lets the architecture follow.",
    heroImage: "/legacy/assets/images/single-project/pdf/single-project-pdf-1-2.png",
    modules: [
      { slug: "meydan-horizon", title: "Meydan Horizon", kind: "CUSTOM", sortOrder: 10, content: { text: "Meydan Horizon places Seven X Seven within a measured urban district shaped by movement, water, and direct access to Dubai's business and cultural centers. The address gives residents a quieter daily rhythm while keeping Downtown, DIFC, DXB, and Ras Al Khor within practical reach.", images: ["/legacy/assets/images/single-project/pdf/seven-x-seven-first-fold.jpg"], items: [{ value: "10", label: "Min. Ras Al Khor" }, { value: "10", label: "Min. Downtown Dubai" }, { value: "10", label: "Min. DXB Airport" }] } },
      { slug: "location", title: "Location", kind: "LOCATION", sortOrder: 20, content: { mapUrl: "https://maps.google.com/maps?q=25.182556%2C55.32325&z=16&output=embed", text: "Set between Meydan, Ras Al Khor, and Downtown Dubai, Seven X Seven connects daily privacy with efficient access to work, leisure, aviation, and nature. Travel times are organized around the routes residents are most likely to use.", items: [{ value: "8 mins", label: "Ras Al Khor Wildlife Sanctuary" }, { value: "13 mins", label: "Dubai Design District" }, { value: "15 mins", label: "Business Bay" }, { value: "18 mins", label: "Burj Khalifa / Dubai Mall" }, { value: "20 mins", label: "Dubai Hills Golf Club" }, { value: "25 mins", label: "Burj Al Arab" }, { value: "11 mins", label: "Meydan Grandstand and Racecourse" }, { value: "14 mins", label: "Dubai Festival City Mall" }, { value: "14 mins", label: "Dubai International Airport" }, { value: "16 mins", label: "Dubai International Financial Centre" }, { value: "22 mins", label: "Dubai Creek Golf and Yacht Club" }, { value: "42 mins", label: "Palm Jumeirah" }] } },
      { slug: "tour", title: "3D Tour", kind: "VIDEO", sortOrder: 30, content: { text: "Explore the project’s arrival, facade rhythm, amenity sequence, and skyline relationship.", images: ["/legacy/assets/images/project-media/sxs/facade%20front%202.png", "/legacy/assets/images/project-media/sxs/facade%20right%201.png", "/legacy/assets/images/project-media/sxs/facade%20back.png"] } },
      { slug: "amenities", title: "Amenities", kind: "GALLERY", sortOrder: 40, content: { text: "Amenities are arranged as a quiet extension of the residence: water, wellness, lounge, landscape, and skyline moments working together rather than competing for attention.", images: ["/legacy/assets/images/single-project/pdf/single-project-pdf-1-6.jpg", "/legacy/assets/images/single-project/pdf/single-project-pdf-1-7.jpg", "/legacy/assets/images/single-project/pdf/single-project-2/extracted-07.jpg", "/legacy/assets/images/project-media/sxs/Facade%20left%201.png", "/legacy/assets/images/single-project/pdf/single-project-pdf-1-1.jpg"], items: ["Amenity Sequence", "Residence Lounge", "Tower Profile", "Facade View", "Skyline View"].map((label) => ({ label })) } },
      calmPanel("Calm carried\nthrough every", "From the pool edge to the tower envelope, the project favors softened light, composed materials, and outdoor rooms that let the city remain present without overwhelming the home.", "/legacy/assets/images/single-project/pdf/seven-x-seven-pool-hero.jpg", "Seven X Seven"), floorPlans("Seven X Seven", "Review indicative layouts designed around clear arrival, efficient circulation, privacy between rooms, and outdoor edges that extend everyday living."), paymentPlan("Seven X Seven", "Payment milestones are structured for clarity across reservation, construction progress, completion, and post-handover settlement. Final percentages are confirmed during availability review.", [{ value: "10%", label: "On booking", text: "Reservation milestone and expression of intent." }, { value: "40%", label: "During construction", text: "Staged payments linked to development progress." }, { value: "40%", label: "On completion", text: "Balance due at handover and title transfer." }, { value: "10%", label: "After handover", text: "Optional settlement window subject to offer terms." }]),
    ],
  },
  "emerald-villa": {
    tagline: "A private rhythm\nheld by landscape",
    description: "Emerald Villa is composed around privacy, garden arrival, and a softer rhythm of family-scaled spaces. The property balances a quiet residential mood with the clarity and discipline expected from a KPD development.",
    heroImage: "/legacy/assets/images/project-media/Emerald%20Villa/2_EH-8k%201.jpeg",
    modules: [
      { slug: "garden-privacy", title: "Garden-led privacy", kind: "CUSTOM", sortOrder: 10, content: { text: "Emerald Villa is organized around planted arrival, private outdoor rooms, and a calm family rhythm. The address privileges stillness first, then connects that quiet setting to retail, schools, wellness, and the city's main business districts.", images: ["/legacy/assets/images/project-media/Emerald%20Villa/2_EH-8k%201.jpeg"], items: [{ value: "5", label: "Min. Daily retail" }, { value: "12", label: "Min. Schools" }, { value: "20", label: "Min. Downtown Dubai" }] } },
      { slug: "location", title: "Location", kind: "LOCATION", sortOrder: 20, content: { mapUrl: "https://maps.google.com/maps?q=Emerald%20Hills%20Dubai&z=16&output=embed", text: "Positioned for a private Dubai lifestyle, Emerald Villa connects garden-led residential calm with nearby retail, schools, wellness, and city access.", items: [{ value: "5 mins", label: "Daily retail and cafes" }, { value: "8 mins", label: "Community park" }, { value: "10 mins", label: "International schools" }, { value: "12 mins", label: "Golf and club house" }, { value: "15 mins", label: "Business Bay" }, { value: "20 mins", label: "Downtown Dubai" }, { value: "12 mins", label: "Wellness and fitness clubs" }, { value: "18 mins", label: "Dubai Mall" }, { value: "20 mins", label: "Dubai International Airport" }, { value: "24 mins", label: "Dubai Design District" }, { value: "28 mins", label: "Palm Jumeirah" }, { value: "35 mins", label: "Al Maktoum corridor" }] } },
      { slug: "tour", title: "3D Tour", kind: "VIDEO", sortOrder: 30, content: { images: ["/legacy/assets/images/project-media/Emerald%20Villa/4%20(1).jpg", "/legacy/assets/images/project-media/Emerald%20Villa/12_2.jpg", "/legacy/assets/images/project-media/Emerald%20Villa/8.jpg"], text: "Explore the project’s layered facade, garden arrival, and composed residential interiors." } },
      { slug: "amenities", title: "Amenities", kind: "GALLERY", sortOrder: 40, content: { text: "Emerald Villa brings together private wellness, garden rooms, family gathering spaces, and hospitality cues to create a home that feels composed from arrival to retreat.", images: ["/legacy/assets/images/project-media/Emerald%20Villa/tm2161_vp18_interior_lobby_rev07.jpg", "/legacy/assets/images/project-media/Emerald%20Villa/tm2161_vp20_interior_1brliving_rev07.jpg", "/legacy/assets/images/project-media/Emerald%20Villa/tm2161_vp21_interior_1brbedroom_rev04.jpg", "/legacy/assets/images/project-media/Emerald%20Villa/tm2161_vp26_interior_3bdrkitchen_b_rev06.jpg", "/legacy/assets/images/project-media/Emerald%20Villa/tm2161_vp30_interior_3bd_living_dusk_rev06.jpg"], items: ["Arrival Lobby", "Living Lounge", "Private Suite", "Kitchen Gallery", "Evening Living"].map((label) => ({ label })) } },
      calmPanel("Privacy held\nin the garden", "The villa's living spaces are softened by planted edges, natural light, and outdoor rooms that make daily life feel protected without closing it off from the landscape.", "/legacy/assets/images/project-media/Emerald%20Villa/12.jpg", "Emerald Villa"), floorPlans("Emerald Villa", "Indicative villa layouts prioritize arrival clarity, generous family gathering, private bedroom wings, and outdoor extensions that keep garden life close to the daily plan."), paymentPlan("Emerald Villa", "Milestones are structured around reservation, progress, handover, and optional post-handover settlement, with final terms confirmed during availability review.", [{ value: "15%", label: "On booking", text: "Reservation and initial allocation milestone." }, { value: "35%", label: "During construction", text: "Staged payments aligned to project progress." }, { value: "40%", label: "On completion", text: "Balance due at handover and transfer." }, { value: "10%", label: "After handover", text: "Optional settlement window subject to offer terms." }]),
    ],
  },
  "dubai-hills-mansion": {
    tagline: "Mansion living\nwith quiet scale",
    description: "Dubai Hills Mansion is shaped for expansive family living, garden arrival, and a hospitality-led daily experience. The residence frames privacy, scale, and ease as one coherent property logic.",
    heroImage: "/legacy/assets/images/library/an-outdoor-front-yard-area-with-a-path-between-two-2026-03-18-12-14-30-utc.jpg",
    modules: [
      { slug: "dubai-hills-estate", title: "Dubai Hills Estate", kind: "CUSTOM", sortOrder: 10, content: { text: "Dubai Hills Mansion is positioned within a landscape-led district where golf, parks, retail, schools, and city access sit close to a private family address. The location gives the residence daily convenience without compromising the sense of scale and retreat.", images: ["/legacy/assets/images/project-media/Dubai%20Hills%20Mansion/4_plex_rev_02_final.jpg"], items: [{ value: "5", label: "Min. Golf club" }, { value: "10", label: "Min. Dubai Hills Mall" }, { value: "20", label: "Min. Downtown Dubai" }] } },
      { slug: "location", title: "Location", kind: "LOCATION", sortOrder: 20, content: { mapUrl: "https://maps.google.com/maps?q=Dubai%20Hills%20Estate%2C%20Dubai&z=16&output=embed", text: "Located within Dubai Hills Estate, the mansion connects private residential scale with golf, retail, schools, parks, and direct city access.", items: [{ value: "5 mins", label: "Dubai Hills Golf Club" }, { value: "7 mins", label: "Community parks" }, { value: "8 mins", label: "Dubai Hills Mall" }, { value: "10 mins", label: "International schools" }, { value: "15 mins", label: "Mall of the Emirates" }, { value: "18 mins", label: "Business Bay" }, { value: "12 mins", label: "Healthcare and wellness" }, { value: "20 mins", label: "Downtown Dubai" }, { value: "22 mins", label: "Dubai Marina" }, { value: "25 mins", label: "DIFC" }, { value: "28 mins", label: "Palm Jumeirah" }, { value: "30 mins", label: "Dubai International Airport" }] } },
      { slug: "tour", title: "3D Tour", kind: "VIDEO", sortOrder: 30, content: { images: ["/legacy/assets/images/project-media/Dubai%20Hills%20Mansion/6_plex_front_rev_final_1.jpg", "/legacy/assets/images/library/modern-luxury-house-with-landscaped-garden-under-a-2026-03-09-02-55-27-utc.jpg", "/legacy/assets/images/library/suburban-dubai-cityscape-2026-03-20-00-15-57-utc.jpg"], text: "Explore the residence’s landscaped arrival, private rooms, wellness spaces, and garden-facing interiors." } },
      { slug: "amenities", title: "Amenities", kind: "GALLERY", sortOrder: 40, content: { text: "Dubai Hills Mansion brings together generous indoor rooms, private outdoor amenities, wellness spaces, and family-focused landscape moments within a mansion-scale setting.", images: ["/legacy/assets/images/project-media/Dubai%20Hills%20Mansion/4462_yas_acers_orchids_bathroom_dark_scheme_draft_002_tg_1.jpg", "/legacy/assets/images/project-media/Dubai%20Hills%20Mansion/4462_yas_acers_orchids_bedroom_dark_scheme_draft_002_tg.jpg", "/legacy/assets/images/project-media/Dubai%20Hills%20Mansion/4462_yas_acers_orchids_kitchen_light_scheme_draft_002_abe.jpg", "/legacy/assets/images/project-media/Dubai%20Hills%20Mansion/4462_yas_acers_orchids_living_vignette_light_scheme_draft_00.jpg", "/legacy/assets/images/project-media/Dubai%20Hills%20Mansion/4_plex_rev_02_final.jpg"], items: ["Wellness Bath", "Evening Bedroom", "Chef Kitchen", "Garden Living", "Landscape Arrival"].map((label) => ({ label })) } },
      calmPanel("Scale softened\nby landscape", "The mansion's generous rooms are balanced by garden views, shaded edges, and warm interior surfaces, creating a residence that feels composed rather than oversized.", "/legacy/assets/images/project-media/Dubai%20Hills%20Mansion/4462_yas_acers_orchids_living_vignette_light_scheme_draft_00.jpg", "Dubai Hills Mansion"), floorPlans("Dubai Hills Mansion", "Indicative mansion layouts organize arrival, entertaining, family privacy, guest accommodation, and outdoor living into a clear residential sequence."), paymentPlan("Dubai Hills Mansion", "Milestones are structured around reservation, progress, handover, and optional post-handover settlement, with final terms confirmed during availability review.", [{ value: "15%", label: "On booking", text: "Reservation and initial allocation milestone." }, { value: "35%", label: "During construction", text: "Staged payments aligned to project progress." }, { value: "40%", label: "On completion", text: "Balance due at handover and transfer." }, { value: "10%", label: "After handover", text: "Optional settlement window subject to offer terms." }]),
    ],
  },
};
