/// Canonical module blueprints transcribed from the delivered development pages.
/// They bootstrap existing legacy projects into the CMS without rewriting copy.
type Module = { slug: string; title: string; kind: "GALLERY" | "FLOOR_PLAN" | "SPECIFICATIONS" | "LOCATION" | "VIDEO" | "BROCHURE" | "CUSTOM"; sortOrder: number; content: object };
type Template = { tagline: string; description: string; modules: Module[] };

const floorPlans = (name: string, text: string): Module => ({ slug: "floor-plans", title: "Floor Plans", kind: "FLOOR_PLAN", sortOrder: 50, content: { text, items: ["A", "B", "C"].map((label) => ({ label: `Type ${label}`, image: `/legacy/assets/images/floor-plans/seven-x-seven-type-${label.toLowerCase()}.svg`, url: `/legacy/contact.html?project=${encodeURIComponent(name)}&request=floor-plan-${label.toLowerCase()}` })) } });
const paymentPlan = (booking: string, construction: string): Module => ({ slug: "payment-plan", title: "Payment Plan", kind: "CUSTOM", sortOrder: 60, content: { text: "Payment milestones are structured for clarity across reservation, construction progress, completion, and post-handover settlement. Final percentages are confirmed during availability review.", items: [{ value: booking, label: "On booking" }, { value: construction, label: "During construction" }, { value: "40%", label: "On completion" }, { value: "10%", label: "After handover" }] } });
const calmPanel = (title: string, text: string, image: string, name: string): Module => ({ slug: "brochure", title, kind: "CUSTOM", sortOrder: 45, content: { presentation: "calm", text, images: [image], url: `/legacy/contact.html?project=${encodeURIComponent(name)}&request=brochure` } });

export const legacyProjectTemplates: Record<string, Template> = {
  "seven-x-seven": {
    tagline: "An address shaped by restraint",
    description: "Seven X Seven Residences sits within Meydan Horizon, planned around measured city access and the quiet rhythm of everyday living. The brief begins with how the home is used - arrival, light, and privacy - and lets the architecture follow.",
    modules: [
      { slug: "meydan-horizon", title: "Meydan Horizon", kind: "CUSTOM", sortOrder: 10, content: { text: "Meydan Horizon places Seven X Seven within a measured urban district shaped by movement, water, and direct access to Dubai's business and cultural centers. The address gives residents a quieter daily rhythm while keeping Downtown, DIFC, DXB, and Ras Al Khor within practical reach.", images: ["/legacy/assets/images/single-project/pdf/seven-x-seven-first-fold.jpg"], items: [{ value: "12", label: "Min. Downtown Dubai" }, { value: "15", label: "Min. DIFC" }, { value: "18", label: "Min. DXB" }] } },
      { slug: "location", title: "Location", kind: "LOCATION", sortOrder: 20, content: { mapUrl: "https://maps.google.com/maps?q=25.182556%2C55.32325&z=16&output=embed", text: "Set between Meydan, Ras Al Khor, and Downtown Dubai, Seven X Seven connects daily privacy with efficient access to work, leisure, aviation, and nature.", items: [{ value: "8 mins", label: "Ras Al Khor Wildlife Sanctuary" }, { value: "12 mins", label: "Downtown Dubai" }, { value: "15 mins", label: "DIFC" }, { value: "18 mins", label: "Dubai International Airport" }, { value: "20 mins", label: "Dubai Design District" }, { value: "25 mins", label: "Jumeirah Beach" }] } },
      { slug: "tour", title: "3D Tour", kind: "VIDEO", sortOrder: 30, content: { text: "Explore the project’s arrival, facade rhythm, amenity sequence, and skyline relationship.", images: ["/legacy/assets/images/single-project/pdf/single-project-pdf-1-1.jpg", "/legacy/assets/images/single-project/pdf/single-project-pdf-1-6.jpg", "/legacy/assets/images/single-project/pdf/single-project-pdf-1-7.jpg"] } },
      { slug: "amenities", title: "Amenities", kind: "GALLERY", sortOrder: 40, content: { text: "Amenities are arranged as a quiet extension of the residence: water, wellness, lounge, landscape, and skyline moments working together rather than competing for attention.", images: ["/legacy/assets/images/single-project/pdf/single-project-pdf-1-6.jpg", "/legacy/assets/images/single-project/pdf/single-project-pdf-1-7.jpg", "/legacy/assets/images/single-project/pdf/single-project-2/extracted-07.jpg", "/legacy/assets/images/project-media/sxs/Facade%20left%201.png", "/legacy/assets/images/single-project/pdf/single-project-pdf-1-1.jpg"], items: ["Amenity Sequence", "Residence Lounge", "Tower Profile", "Facade View", "Skyline View"].map((label) => ({ label })) } },
      calmPanel("Calm carried through every detail", "From the pool edge to the tower envelope, the project favors softened light, composed materials, and outdoor rooms that let the city remain present without overwhelming the home.", "/legacy/assets/images/single-project/pdf/single-project-pdf-1-1.jpg", "Seven X Seven"), floorPlans("Seven X Seven", "Review indicative layouts designed around clear arrival, efficient circulation, privacy between rooms, and outdoor edges that extend everyday living."), paymentPlan("10%", "40%"),
    ],
  },
  "emerald-villa": {
    tagline: "A private rhythm held by landscape",
    description: "Emerald Villa is composed around privacy, garden arrival, and a softer rhythm of family-scaled spaces. The property balances a quiet residential mood with the clarity and discipline expected from a KPD development.",
    modules: [
      { slug: "garden-privacy", title: "Garden-led privacy", kind: "CUSTOM", sortOrder: 10, content: { text: "Emerald Villa is organized around planted arrival, private outdoor rooms, and a calm family rhythm. The address privileges stillness first, then connects that quiet setting to retail, schools, wellness, and the city's main business districts.", images: ["/legacy/assets/images/project-media/Emerald%20Villa/2_EH-8k%201.jpeg"], items: [{ value: "5", label: "Min. Daily retail" }, { value: "12", label: "Min. Schools" }, { value: "20", label: "Min. Downtown Dubai" }] } },
      { slug: "location", title: "Location", kind: "LOCATION", sortOrder: 20, content: { mapUrl: "https://maps.google.com/maps?q=Emerald%20Hills%20Dubai&z=16&output=embed", text: "Positioned for a private Dubai lifestyle, Emerald Villa connects garden-led residential calm with nearby retail, schools, wellness, and city access.", items: [{ value: "5 mins", label: "Daily retail and cafes" }, { value: "10 mins", label: "International schools" }, { value: "12 mins", label: "Golf and club house" }, { value: "15 mins", label: "Business Bay" }, { value: "20 mins", label: "Downtown Dubai" }, { value: "20 mins", label: "Dubai International Airport" }] } },
      { slug: "tour", title: "3D Tour", kind: "VIDEO", sortOrder: 30, content: { images: ["/legacy/assets/images/project-media/Emerald%20Villa/4%20(1).jpg", "/legacy/assets/images/project-media/Emerald%20Villa/12_2.jpg", "/legacy/assets/images/project-media/Emerald%20Villa/8.jpg"], text: "Explore the project’s layered facade, garden arrival, and composed residential interiors." } },
      { slug: "amenities", title: "Amenities", kind: "GALLERY", sortOrder: 40, content: { text: "Emerald Villa brings together private wellness, garden rooms, family gathering spaces, and hospitality cues to create a home that feels composed from arrival to retreat.", images: ["/legacy/assets/images/project-media/Emerald%20Villa/tm2161_vp18_interior_lobby_rev07.jpg", "/legacy/assets/images/project-media/Emerald%20Villa/tm2161_vp20_interior_1brliving_rev07.jpg", "/legacy/assets/images/project-media/Emerald%20Villa/tm2161_vp21_interior_1brbedroom_rev04.jpg", "/legacy/assets/images/project-media/Emerald%20Villa/tm2161_vp26_interior_3bdrkitchen_b_rev06.jpg", "/legacy/assets/images/project-media/Emerald%20Villa/tm2161_vp30_interior_3bd_living_dusk_rev06.jpg"], items: ["Arrival Lobby", "Living Lounge", "Private Suite", "Kitchen Gallery", "Evening Living"].map((label) => ({ label })) } },
      calmPanel("Privacy held in the garden", "The villa's living spaces are softened by planted edges, natural light, and outdoor rooms that make daily life feel protected without closing it off from the landscape.", "/legacy/assets/images/project-media/Emerald%20Villa/12.jpg", "Emerald Villa"), floorPlans("Emerald Villa", "Indicative villa layouts prioritize arrival clarity, generous family gathering, private bedroom wings, and outdoor extensions that keep garden life close to the daily plan."), paymentPlan("15%", "35%"),
    ],
  },
  "dubai-hills-mansion": {
    tagline: "Mansion living with quiet scale",
    description: "Dubai Hills Mansion is shaped for expansive family living, garden arrival, and a hospitality-led daily experience. The residence frames privacy, scale, and ease as one coherent property logic.",
    modules: [
      { slug: "dubai-hills-estate", title: "Dubai Hills Estate", kind: "CUSTOM", sortOrder: 10, content: { text: "Dubai Hills Mansion is positioned within a landscape-led district where golf, parks, retail, schools, and city access sit close to a private family address. The location gives the residence daily convenience without compromising the sense of scale and retreat.", images: ["/legacy/assets/images/project-media/Dubai%20Hills%20Mansion/4_plex_rev_02_final.jpg"], items: [{ value: "5", label: "Min. Retail" }, { value: "10", label: "Min. Golf" }, { value: "20", label: "Min. Downtown Dubai" }] } },
      { slug: "location", title: "Location", kind: "LOCATION", sortOrder: 20, content: { mapUrl: "https://maps.google.com/maps?q=Dubai%20Hills%20Estate%2C%20Dubai&z=16&output=embed", text: "Located within Dubai Hills Estate, the mansion connects private residential scale with golf, retail, schools, parks, and direct city access.", items: [{ value: "5 mins", label: "Dubai Hills Mall" }, { value: "10 mins", label: "Dubai Hills Golf Club" }, { value: "12 mins", label: "International schools" }, { value: "15 mins", label: "Business Bay" }, { value: "20 mins", label: "Downtown Dubai" }, { value: "25 mins", label: "Dubai International Airport" }] } },
      { slug: "tour", title: "3D Tour", kind: "VIDEO", sortOrder: 30, content: { images: ["/legacy/assets/images/project-media/Dubai%20Hills%20Mansion/6_plex_front_rev_final_1.jpg", "/legacy/assets/images/project-media/Dubai%20Hills%20Mansion/4_plex_rev_02_final.jpg"], text: "Explore the residence’s landscaped arrival, private rooms, wellness spaces, and garden-facing interiors." } },
      { slug: "amenities", title: "Amenities", kind: "GALLERY", sortOrder: 40, content: { text: "Dubai Hills Mansion brings together generous indoor rooms, private outdoor amenities, wellness spaces, and family-focused landscape moments within a mansion-scale setting.", images: ["/legacy/assets/images/project-media/Dubai%20Hills%20Mansion/4462_yas_acers_orchids_bathroom_dark_scheme_draft_002_tg_1.jpg", "/legacy/assets/images/project-media/Dubai%20Hills%20Mansion/4462_yas_acers_orchids_bedroom_dark_scheme_draft_002_tg.jpg", "/legacy/assets/images/project-media/Dubai%20Hills%20Mansion/4462_yas_acers_orchids_kitchen_light_scheme_draft_002_abe.jpg", "/legacy/assets/images/project-media/Dubai%20Hills%20Mansion/4462_yas_acers_orchids_living_vignette_light_scheme_draft_00.jpg", "/legacy/assets/images/project-media/Dubai%20Hills%20Mansion/4_plex_rev_02_final.jpg"], items: ["Wellness Bath", "Evening Bedroom", "Chef Kitchen", "Garden Living", "Landscape Arrival"].map((label) => ({ label })) } },
      calmPanel("Scale softened by landscape", "The mansion's generous rooms are balanced by garden views, shaded edges, and warm interior surfaces, creating a residence that feels composed rather than oversized.", "/legacy/assets/images/project-media/Dubai%20Hills%20Mansion/4_plex_rev_02_final.jpg", "Dubai Hills Mansion"), floorPlans("Dubai Hills Mansion", "Indicative mansion layouts organize arrival, entertaining, family privacy, guest accommodation, and outdoor living into a clear residential sequence."), paymentPlan("15%", "35%"),
    ],
  },
};
