/// Canonical Legacy-page content as delivered by the client (public/legacy/
/// legacy.html). Single source of truth: the public page renders these values
/// when the CMS has none, and the admin editor pre-fills from them. Pure data —
/// safe to import from client components.

export type LegacyMilestone = { year?: string; title?: string; summary?: string; body?: string; image?: string };
export type LegacyContent = { heading?: string; text?: string; image?: string; timeline?: LegacyMilestone[] };

export const legacyDefaults: Required<Pick<LegacyContent, "heading" | "text" | "image">> & { timeline: LegacyMilestone[] } = {
  heading: "A long-horizon\nplatform",
  text: "From Tokyo to Dubai, the KPD platform is shaped by disciplined capital, measured execution, and development value built to hold over time.",
  image: "/legacy/assets/images/about/about-hero.jpg",
  timeline: [
    { year: "2014", title: "Foundations of the platform", summary: "The early phase centered on site logic, underwriting rigor, and a belief that every design decision should begin with commercial clarity.", body: "The first chapter was less about scale and more about method. Opportunity screening, demand discipline, and feasibility-led thinking became the base layer for how the platform would evaluate, prioritize, and shape future developments.", image: "/legacy/assets/images/library/aerial-view-of-osaka-city-from-sky-building-bird-2026-03-17-14-45-17-utc.jpg" },
    { year: "2016", title: "Boutique residential focus sharpens", summary: "Early residential briefs helped define a clearer position around privacy, livability, and product quality over volume-driven development.", body: "The residential lens matured into a stronger product philosophy. Layout efficiency, calm arrival experiences, and long-term habitability started to influence how the platform translated commercial strategy into the language of everyday living.", image: "/legacy/assets/images/library/downtown-urban-city-in-japan-2026-03-10-03-53-46-utc.jpg" },
    { year: "2018", title: "Hospitality and mixed-use capability expands", summary: "The platform broadened beyond one asset type, bringing placemaking, operational thinking, and return discipline into a wider development model.", body: "Hospitality and mixed-use opportunities introduced a richer operating layer. The development story now had to hold together brand, user flow, public realm, and asset performance in one cohesive strategy rather than as separate conversations.", image: "/legacy/assets/images/library/kumamoto-japan-downtown-cityscape-on-the-shirakaw-2026-03-24-11-40-22-utc.jpg" },
    { year: "2020", title: "Execution systems become more deliberate", summary: "Consultant alignment, delivery governance, and budget coordination matured into a more controlled framework for moving from concept to handover.", body: "This phase deepened the platform's delivery confidence. Programme logic, cost control, design decision-making, and handover preparedness were treated as a single operating system rather than isolated workstreams.", image: "/legacy/assets/images/library/tokyo-japan-at-ochanomizu-the-district-is-home-t-2026-04-13-23-44-40-utc.jpg" },
    { year: "2023", title: "Regional ambition takes a clearer shape", summary: "A stronger Middle East lens sharpened the platform's opportunity selection around urban demand, investor confidence, and resilient end-user value.", body: "The legacy was no longer just operational; it became directional. Market selection, product timing, and the balance between identity and commercial logic began to point more clearly toward a refined regional platform and a sharper development voice.", image: "/legacy/assets/images/library/modern-skyscraper-at-japan-with-blue-facade-2026-03-25-23-22-32-utc.jpg" },
    { year: "2026", title: "Emerald Villa marks the current chapter", summary: "The present expression of the legacy is more focused: boutique scale, stronger identity, and developments shaped for enduring value rather than short-lived momentum.", body: "The current moment shows a more distilled version of the story. Projects like Emerald Villa and Dubai Hills Mansion reflect the platform's move toward precise scale, elevated livability, and a development process that remains calm, commercially grounded, and durable by design.", image: "/legacy/assets/images/library/yokohama-bay-at-night-2026-03-24-23-17-41-utc.jpg" },
  ],
};
