import { db } from "@/lib/db";

type Block = { type?: string; heading?: string; text?: string; image?: string };
const milestones = [
  ["2014", "Foundations of the platform", "The early phase centered on site logic, underwriting rigor, and a belief that every design decision should begin with commercial clarity.", "The first chapter was less about scale and more about method. Opportunity screening, demand discipline, and feasibility-led thinking became the base layer for how the platform would evaluate, prioritize, and shape future developments.", "/legacy/assets/images/library/aerial-view-of-osaka-city-from-sky-building-bird-2026-03-17-14-45-17-utc.jpg"],
  ["2016", "Boutique residential focus sharpens", "Early residential briefs helped define a clearer position around privacy, livability, and product quality over volume-driven development.", "The residential lens matured into a stronger product philosophy. Layout efficiency, calm arrival experiences, and long-term habitability started to influence how the platform translated commercial strategy into everyday living.", "/legacy/assets/images/library/downtown-urban-city-in-japan-2026-03-10-03-53-46-utc.jpg"],
  ["2018", "Hospitality and mixed-use capability expands", "The platform broadened beyond one asset type, bringing placemaking, operational thinking, and return discipline into a wider development model.", "Hospitality and mixed-use opportunities introduced a richer operating layer, holding together brand, user flow, public realm, and asset performance in one cohesive strategy.", "/legacy/assets/images/library/kumamoto-japan-downtown-cityscape-on-the-shirakaw-2026-03-24-11-40-22-utc.jpg"],
  ["2020", "Execution systems become more deliberate", "Consultant alignment, delivery governance, and budget coordination matured into a more controlled framework for moving from concept to handover.", "Programme logic, cost control, design decision-making, and handover preparedness were treated as a single operating system rather than isolated workstreams.", "/legacy/assets/images/library/tokyo-japan-at-ochanomizu-the-district-is-home-t-2026-04-13-23-44-40-utc.jpg"],
  ["2023", "Regional ambition takes a clearer shape", "A stronger Middle East lens sharpened the platform's opportunity selection around urban demand, investor confidence, and resilient end-user value.", "Market selection, product timing, and the balance between identity and commercial logic began to point more clearly toward a refined regional platform.", "/legacy/assets/images/library/modern-skyscraper-at-japan-with-blue-facade-2026-03-25-23-22-32-utc.jpg"],
  ["2026", "Emerald Villa marks the current chapter", "The present expression of the legacy is more focused: boutique scale, stronger identity, and developments shaped for enduring value.", "Projects like Emerald Villa and Dubai Hills Mansion reflect the platform's move toward precise scale, elevated livability, and a commercially grounded process.", "/legacy/assets/images/library/yokohama-bay-at-night-2026-03-24-23-17-41-utc.jpg"],
] as const;

export const metadata = { title: "Legacy", description: "The long-horizon KPD platform, from Tokyo to Dubai." };
export const dynamic = "force-dynamic";
export default async function LegacyPage() {
  let blocks: Block[] = [];
  try { const page = await db.staticPage.findUnique({ where: { slug: "legacy" } }); if (Array.isArray(page?.content)) blocks = page.content as Block[]; } catch {}
  const hero = blocks.find((block) => block.type === "hero");
  return <div className="legacy-design-page"><div className="legacy-main page-reference-main" id="top"><section className="page-reference-hero" aria-label="Legacy"><img src={hero?.image || "/legacy/assets/images/about/about-hero.jpg"} alt="Tokyo alleyway and Japanese hospitality context" /><div className="page-reference-hero-copy motion-reveal"><span>Legacy</span><h1>{hero?.heading || <>A long-horizon<br />platform</>}</h1><p>{hero?.text || "From Tokyo to Dubai, the KPD platform is shaped by disciplined capital, measured execution, and development value built to hold over time."}</p></div></section><section className="legacy-timeline-section kpd-section" id="legacy-timeline" aria-label="Legacy milestones"><div className="legacy-timeline">{milestones.map(([year, title, summary, body, image], index) => <div className={`legacy-timeline-row ${index % 2 ? "is-right" : "is-left"}`} key={year}><details className={`legacy-timeline-item timeline-item ${index % 2 ? "is-right" : "is-left"}`} open={index === 0}><summary><span className="legacy-year">{year}</span><span className="legacy-summary-copy"><strong>{title}</strong><span>{summary}</span></span></summary><div className="legacy-timeline-body"><p>{body}</p></div></details><figure className="legacy-timeline-media"><img src={image} alt={`Legacy milestone ${year}`} /></figure></div>)}</div></section></div></div>;
}
