import Link from "next/link";

/// Shared public footer. Links point to Next.js routes where available and
/// deliberately retain legacy URLs until their matching template is migrated.
export function SiteFooter({ email, newsletterNote }: { email?: string; newsletterNote?: string }) {
  return <footer className="section_footer" id="footer"><div className="footer_container">
    <div className="footer_header"><Link href="/" aria-label="Kasumigaseki Properties Development home" className="footer_logo_link"><img src="/legacy/assets/images/brand/kasumigaseki-logo-horizontal-all-white.svg" loading="lazy" width="358" alt="Kasumigaseki Properties Development" className="footer_logo" /></Link></div>
    <div className="footer_links"><div className="footer_links_col_container">
      <div className="footer_links_col"><h3 className="footer_links_title text-size-footer">Development</h3><ul role="list" className="footer_links_list"><li className="footer_links_item"><Link href="/developments/seven-x-seven" className="footer_link text-size-footer">Seven X Seven Residences</Link></li><li className="footer_links_item"><Link href="/developments/emerald-villa" className="footer_link text-size-footer">Emerald Villa</Link></li><li className="footer_links_item"><Link href="/developments/dubai-hills-mansion" className="footer_link text-size-footer">Dubai Hills Mansion</Link></li></ul></div>
      <div className="footer_links_col"><h3 className="footer_links_title text-size-footer">Company</h3><ul role="list" className="footer_links_list"><li className="footer_links_item"><Link href="/legacy/about-us.html" className="footer_link text-size-footer">About Us</Link></li><li className="footer_links_item"><Link href="/legacy/legacy.html" className="footer_link text-size-footer">Legacy</Link></li><li className="footer_links_item"><Link href="/legacy/invest-in-dubai.html" className="footer_link text-size-footer">Investor Guide</Link></li></ul></div>
      <div className="footer_links_col"><h3 className="footer_links_title text-size-footer">Media</h3><ul role="list" className="footer_links_list"><li className="footer_links_item"><Link href="/legacy/news.html" className="footer_link text-size-footer">News &amp; Updates</Link></li><li className="footer_links_item"><Link href="/contact" className="footer_link text-size-footer">Contact Us</Link></li></ul></div>
    </div><div className="footer_links_newsletter"><h3 className="footer_links_title text-size-footer">Stay in the know</h3><p className="footer_newsletter_terms text-size-small">{newsletterNote || "Contact the KPD team to receive company and project updates."}{email ? <><br /><a className="link" href={`mailto:${email}`}>{email}</a></> : null}</p></div></div>
    <div className="footer_legal_social footer_links"><div className="footer_legal_left"><ul role="list" className="footer_links_row"><li className="footer_links_item footer_links_legal_item"><Link href="/legacy/terms.html" className="footer_link text-size-footer">Terms of Use</Link></li><li className="footer_links_item footer_links_legal_item"><Link href="/legacy/privacy-policy.html" className="footer_link text-size-footer">Privacy</Link></li><li className="footer_links_item footer_links_legal_item"><Link href="/legacy/cookie-policy.html" className="footer_link text-size-footer">Cookie Policy</Link></li></ul></div><div className="footer_legal_text text-size-footer">Kasumigaseki Properties Development © 2026</div></div>
  </div></footer>;
}
