import { db } from "@/lib/db";

type Block = { type?: string; heading?: string; text?: string; image?: string };
const fallback = {
  heroHeading: "Soulful Places\nEnriched Lives",
  heroText: "Kasumigaseki Properties Development brings institutional discipline, long-term capital, and a decades-deep development track record into one of the world's most dynamic property markets.",
  story: ["Kasumigaseki Properties Development brings the institutional discipline of Kasumigaseki Capital into Dubai's residential market, translating a global platform of development, hospitality, logistics, healthcare, and fund-management experience into a focused UAE pipeline.", "Established to extend that legacy into one of the world's most dynamic property markets, KPD brings institutional discipline, long-term capital, and a decades-deep development track record to the UAE - delivering projects built not just for today's market, but for generations ahead."],
};
function lines(value: string) { return value.split("\n").map((line) => <>{line}<br /></>); }

export const metadata = { title: "About", description: "Learn about Kasumigaseki Properties Development and its Dubai platform." };
export const dynamic = "force-dynamic";
export default async function AboutPage() {
  let blocks: Block[] = [];
  try { const page = await db.staticPage.findUnique({ where: { slug: "about" } }); if (Array.isArray(page?.content)) blocks = page.content as Block[]; } catch {}
  const hero = blocks.find((block) => block.type === "hero");
  const paragraphs = blocks.filter((block) => block.type === "paragraph").map((block) => block.text).filter((text): text is string => Boolean(text));
  const heading = hero?.heading || fallback.heroHeading;
  const story = paragraphs.length ? paragraphs : fallback.story;
  return <div className="about-design-page"><div className="about-main page-reference-main" id="top"><section className="page-reference-hero" aria-label="About Kasumigaseki Properties Development"><img src={hero?.image || "/legacy/assets/images/library/about-advisory-model-presentation.jpg"} alt="Real estate advisory model presentation" /><div className="page-reference-hero-copy motion-reveal"><span>About</span><h1>{lines(heading)}</h1><p>{hero?.text || fallback.heroText}</p></div></section><section className="about-story" id="about"><div className="about-story-grid"><div className="about-story-copy"><h2 className="about-story-title">{lines(heading)}</h2>{story.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div><div className="about-story-media"><img src="/legacy/assets/images/about/pdf/about-pdf-1-2.jpg" alt="KPD office workspace" /></div></div></section><section className="about-mission-vision" id="mission"><article className="about-mission-card"><h2>Our Mission</h2><p>Our mission is to create residential, hospitality, and mixed-use destinations with disciplined feasibility, thoughtful architecture, and delivery control. We shape communities that elevate daily living while protecting long-term value for partners, buyers, and the city around them.</p></article><article className="about-mission-card"><h2>Our Vision</h2><p>Our vision is to become a trusted boutique development platform for the region, where every project is guided by clarity, restraint, and durable performance.</p></article></section><section className="about-chairman" id="chairman"><div className="about-chairman-media"><img src="/legacy/assets/images/team/Alabbar.jpg" alt="Chairman portrait" /></div><div className="about-chairman-copy"><p>The markets we operate in reward patience, clarity, and disciplined execution. KPD was formed to bring those qualities into development decisions, from how land is assessed to how a finished place will be lived in, operated, and valued over time.</p><div className="about-chairman-signature"><strong>Mohammed Alabbar</strong><span>Chairman</span></div></div></section><section className="about-management" id="management"><h2>Executive Management</h2><div className="about-management-grid">{[["Hiroyuki Chiba", "Executive Director", "/legacy/assets/images/team/Chiba.jpg"], ["Ammar Al Tamimi", "Development Director", "/legacy/assets/images/team/Ammar.jpg"], ["Anas Al Khatib", "Commercial Director", "/legacy/assets/images/team/Anas.jpg"]].map(([name, role, image]) => <article className="about-management-card" key={name}><figure><div className="about-management-image"><img src={image} alt={`${name} portrait`} /></div><figcaption><strong>{name}</strong><span>{role}</span></figcaption></figure></article>)}</div></section></div></div>;
}
