// Generates prisma/refresh-legacy-modules.sql - the same reconciliation as
// scripts/refresh-legacy-modules.ts, as plain SQL for the Supabase SQL Editor
// (no direct DB connection or tsx needed on the editor's machine).
//
//   npx tsx scripts/generate-refresh-sql.ts
//
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { legacyProjectTemplates } from "../src/lib/legacy-project-templates";

// Newlines are emitted as an escaped \n inside an E'' string so the file survives
// Windows line-ending conversion (a raw newline in a literal would become CRLF).
const q = (value: string) => {
  const escaped = value.replace(/\\/g, "\\\\").replace(/'/g, "''");
  return value.includes("\n") ? `E'${escaped.replace(/\n/g, "\\n")}'` : `'${escaped}'`;
};
const lines: string[] = [];

lines.push(`-- KPD: reconcile the three delivered development pages with the delivered design.`);
lines.push(`-- Generated by scripts/generate-refresh-sql.ts from src/lib/legacy-project-templates.ts.`);
lines.push(`--`);
lines.push(`-- WARNING: this OVERWRITES the CMS modules (and tagline/description) of seven-x-seven,`);
lines.push(`-- emerald-villa and dubai-hills-mansion with the delivered content, and DELETES modules`);
lines.push(`-- that are not part of the delivered pages (e.g. Emerald's extra "Arrival & Interiors").`);
lines.push(`-- A backup of the affected rows is written first (see "UNDO" at the bottom).`);
lines.push(``);
lines.push(`BEGIN;`);
lines.push(``);
lines.push(`-- 1. Backup (safe to re-run: only created once).`);
lines.push(`CREATE TABLE IF NOT EXISTS project_modules_backup_20261009 AS SELECT * FROM project_modules WHERE false;`);
lines.push(`CREATE TABLE IF NOT EXISTS projects_backup_20261009 AS SELECT * FROM projects WHERE false;`);
lines.push(`INSERT INTO project_modules_backup_20261009 SELECT * FROM project_modules WHERE "projectId" IN (SELECT id FROM projects WHERE slug IN (${Object.keys(legacyProjectTemplates).map(q).join(", ")})) AND NOT EXISTS (SELECT 1 FROM project_modules_backup_20261009);`);
lines.push(`INSERT INTO projects_backup_20261009 SELECT * FROM projects WHERE slug IN (${Object.keys(legacyProjectTemplates).map(q).join(", ")}) AND NOT EXISTS (SELECT 1 FROM projects_backup_20261009);`);
lines.push(``);

for (const [slug, template] of Object.entries(legacyProjectTemplates)) {
  const project = `(SELECT id FROM projects WHERE slug = ${q(slug)})`;
  lines.push(`-- ${slug} ----------------------------------------------------------------`);
  lines.push(`UPDATE projects SET tagline = ${q(template.tagline)}, description = ${q(template.description)}, "updatedAt" = NOW() WHERE slug = ${q(slug)};`);
  for (const module of template.modules) {
    lines.push(`INSERT INTO project_modules ("id", "projectId", "slug", "title", "kind", "profile", "content", "sortOrder", "updatedAt")`);
    lines.push(`VALUES ('mod_' || substr(md5(random()::text || clock_timestamp()::text), 1, 22), ${project}, ${q(module.slug)}, ${q(module.title)}, ${q(module.kind)}::"ModuleKind", 'FULL', $json$${JSON.stringify(module.content)}$json$::jsonb, ${module.sortOrder}, NOW())`);
    lines.push(`ON CONFLICT ("projectId", "slug") DO UPDATE SET "title" = EXCLUDED."title", "kind" = EXCLUDED."kind", "content" = EXCLUDED."content", "sortOrder" = EXCLUDED."sortOrder", "updatedAt" = NOW();`);
  }
  const keep = template.modules.map((module) => q(module.slug)).join(", ");
  lines.push(`DELETE FROM content_versions WHERE "entityType" = 'PROJECT_MODULE' AND "entityId" IN (SELECT id FROM project_modules WHERE "projectId" = ${project} AND slug NOT IN (${keep}));`);
  lines.push(`DELETE FROM project_modules WHERE "projectId" = ${project} AND slug NOT IN (${keep});`);
  lines.push(``);
}

lines.push(`-- 2. Check before committing: every project should list its delivered modules.`);
lines.push(`SELECT p.slug AS project, m.slug AS module, m."sortOrder" FROM project_modules m JOIN projects p ON p.id = m."projectId" WHERE p.slug IN (${Object.keys(legacyProjectTemplates).map(q).join(", ")}) ORDER BY p.slug, m."sortOrder";`);
lines.push(``);
lines.push(`COMMIT;`);
lines.push(``);
lines.push(`-- UNDO (run separately if needed):`);
lines.push(`--   BEGIN;`);
lines.push(`--   DELETE FROM project_modules WHERE "projectId" IN (SELECT id FROM projects WHERE slug IN (${Object.keys(legacyProjectTemplates).map(q).join(", ")}));`);
lines.push(`--   INSERT INTO project_modules SELECT * FROM project_modules_backup_20261009;`);
lines.push(`--   UPDATE projects p SET tagline = b.tagline, description = b.description FROM projects_backup_20261009 b WHERE b.id = p.id;`);
lines.push(`--   COMMIT;`);
lines.push(`-- Public pages re-render within 5 minutes (ISR), or immediately after any admin save.`);

writeFileSync(join(process.cwd(), "prisma", "refresh-legacy-modules.sql"), lines.join("\n") + "\n", "utf8");
console.log("wrote prisma/refresh-legacy-modules.sql");
